return {
    ["Noobini Pizzanini"] = {enabled = true, quality = "Common"},
    ["Lirilí Larilá"] = {enabled = true, quality = "Common"},
    ["Tim Cheese"] = {enabled = true, quality = "Common"},
    ["Fluriflura"] = {enabled = true, quality = "Common"},
    ["Talpa Di Fero"] = {enabled = true, quality = "Common"},
    ["Svinina Bombardino"] = {enabled = true, quality = "Common"},
    ["Pipi Kiwi"] = {enabled = true, quality = "Common"},
    ["Trippi Troppi"] = {enabled = true, quality = "Rare"},
    ["Tung Tung Tung Sahur"] = {enabled = true, quality = "Rare"},
    ["Gangster Footera"] = {enabled = true, quality = "Rare"},
    ["Boneca Ambalabu"] = {enabled = true, quality = "Rare"},
    ["Ta Ta Ta Ta Sahur"] = {enabled = true, quality = "Rare"},
    ["Tric Trac Baraboom"] = {enabled = true, quality = "Rare"},
    ["Bandito Bobritto"] = {enabled = true, quality = "Rare"},
    ["Cacto Hipopotamo"] = {enabled = true, quality = "Rare"},
    ["Cappuccino Assassino"] = {enabled = true, quality = "Epic"},
    ["Brr Brr Patapim"] = {enabled = true, quality = "Epic"},
    ["Trulimero Trulicina"] = {enabled = true, quality = "Epic"},
    ["Bambini Crostini"] = {enabled = true, quality = "Epic"},
    ["Bananita Dolphinita"] = {enabled = true, quality = "Epic"},
    ["Perochello Lemonchello"] = {enabled = true, quality = "Epic"},
    ["Brri Brri Bicus Dicus Bombicus"] = {enabled = true, quality = "Epic"},
    ["Burbaloni Loliloli"] = {enabled = true, quality = "Legendary"},
    ["Chimpanzini Bananini"] = {enabled = true, quality = "Legendary"},
    ["Ballerina Cappuccina"] = {enabled = true, quality = "Legendary"},
    ["Chef Crabracadabra"] = {enabled = true, quality = "Legendary"},
    ["Glorbo Fruttodrillo"] = {enabled = true, quality = "Legendary"},
    ["Blueberrinni Octopusini"] = {enabled = true, quality = "Legendary"},
    ["Lionel Cactuseli"] = {enabled = true, quality = "Legendary"},
    ["Pandaccini Bananini"] = {enabled = true, quality = "Legendary"},
    ["Frigo Camelo"] = {enabled = true, quality = "Mythic"},
    ["Orangutini Ananassini"] = {enabled = true, quality = "Mythic"},
    ["Rhino Toasterino"] = {enabled = true, quality = "Mythic"},
    ["Bombardiro Crocodilo"] = {enabled = true, quality = "Mythic"},
    ["Bombombini Gusini"] = {enabled = true, quality = "Mythic"},
    ["Cavallo Virtuoso"] = {enabled = true, quality = "Mythic"},
    ["Mythic Block"] = {enabled = true, quality = "Mythic"},
    ["Cocofanto Elefanto"] = {enabled = true, quality = "Brainrot God"},
    ["Gattatino Nyanino"] = {enabled = true, quality = "Brainrot God"},
    ["Girafa Celestre"] = {enabled = true, quality = "Brainrot God"},
    ["Tralalero Tralala"] = {enabled = true, quality = "Brainrot God"},
    ["Matteo"] = {enabled = true, quality = "Brainrot God"},
    ["Odin Din Din Dun"] = {enabled = true, quality = "Brainrot God"},
    ["Trenostruzzo Turbo 3000"] = {enabled = true, quality = "Brainrot God"},
    ["Unclito Samito"] = {enabled = true, quality = "Brainrot God"},
    ["Brainrot God Block"] = {enabled = true, quality = "Brainrot God"},
    ["La Vacca Saturno Saturnita"] = {enabled = true, quality = "Secret"},
    ["Los Tralaleritos"] = {enabled = true, quality = "Secret"},
    ["Graipuss Medussi"] = {enabled = true, quality = "Secret"},
    ["La Grande Combinazione"] = {enabled = true, quality = "Secret"},
    ["Chimpanzini Spiderini"] = {enabled = true, quality = "Secret"},
    ["Garama and Madundung"] = {enabled = true, quality = "Secret"},
    ["Las Tralaleritas"] = {enabled = true, quality = "Secret"},
    ["Secret Block"] = {enabled = true, quality = "Secret"},
}
